version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  api:
    build: ./api
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      NOTIFICATIONS_QUEUE_NAME: ${NOTIFICATIONS_QUEUE_NAME}
      NOTIFICATIONS_QUEUE_USER: ${NOTIFICATIONS_QUEUE_USER}
      NOTIFICATIONS_QUEUE_PASSWORD: ${NOTIFICATIONS_QUEUE_PASSWORD}
      NOTIFICATIONS_QUEUE_HOST: ${NOTIFICATIONS_QUEUE_HOST}
      TEST_PORT: ${TEST_PORT}
      TEST_DB_HOST: ${TEST_DB_HOST}
      TEST_DB_USER: ${TEST_DB_USER}
      TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}
      TEST_DB_PORT: ${TEST_DB_PORT}
      TEST_DB_NAME: ${TEST_DB_NAME}
      TEST_SECRET_KEY: ${TEST_SECRET_KEY}
      TEST_NOTIFICATIONS_QUEUE_NAME: ${TEST_NOTIFICATIONS_QUEUE_NAME}
      TEST_NOTIFICATIONS_QUEUE_USER: ${TEST_NOTIFICATIONS_QUEUE_USER}
      TEST_NOTIFICATIONS_QUEUE_PASSWORD: ${TEST_NOTIFICATIONS_QUEUE_PASSWORD}
      TEST_NOTIFICATIONS_QUEUE_HOST: ${TEST_NOTIFICATIONS_QUEUE_HOST}
    ports:
      - "3000:3000"
    restart: on-failure
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
volumes:
  db: